### ISSUE TITLE
error install 

### ISSUE THREAD

**Issue by anubi5egypt** [wssheldon/osintui#11]
![2022-10-26_18-14](https://user-images.githubusercontent.com/42506882/198079482-1297b702-9eed-404b-a2cf-e94043398e96.png)

**Comment by wssheldon** [comment]
Looks like this is related to your installation of `rust` / `Cargo` -- Take a look at these [[0]](https://www.google.com/search?q=this+version+of+cargo+is+older+than+the+2021+edition&oq=%22this+version+of+cargo&aqs=chrome.1.69i57j0i512j0i22i30.6733j0j7&sourceid=chrome&ie=UTF-8) search results on Google for the error you got and see if any of the recommendations there resolve your issue.

[0] - https://www.google.com/search?q=this+version+of+cargo+is+older+than+the+2021+edition&oq=%22this+version+of+cargo&aqs=chrome.1.69i57j0i512j0i22i30.6733j0j7&sourceid=chrome&ie=UTF-8
