### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by kalistamp-dmp** [wssheldon/osintui#12]
How do i run tool after  installation is complete  ?

**Comment by wssheldon** [comment]
After installation, you should be able to just type `osintui` in your terminal, and run the the tool.

**Comment by kalistamp-dmp** [comment]
After installing rust and attempting installation of osintui using cargo i receive the follow error:
( For reference i am using linux os)

installation code entered: 

cargo install osintui

Error received:

warning: build failed, waiting for other jobs to finish...
error: failed to compile `osintui v0.1.1`, intermediate artifacts can be found at `/tmp/cargo-installKX3U8e`
