### ISSUE TITLE
[Feature Request]: Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by jtrv** [wssheldon/osintui#30]
The `.osintui/` directory unnecessarily pollute users' `$HOME` directory.

The [XDGBDS](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) defines where files (such as configs) should be placed with environment variables in order to avoid this.

From the XDGBDS:

> The XDG Base Directory Specification is based on the following concepts:
>
>    There is a single base directory relative to which user-specific data files should be written. This directory is defined by the environment variable $XDG_DATA_HOME.
>
>    There is a single base directory relative to which user-specific configuration files should be written. This directory is defined by the environment variable $XDG_CONFIG_HOME.
>
>    There is a single base directory relative to which user-specific state data should be written. This directory is defined by the environment variable $XDG_STATE_HOME.
>
>    There is a single base directory relative to which user-specific non-essential (cached) data should be written. This directory is defined by the environment variable $XDG_CACHE_HOME.
>
> User-specific executable files may be stored in $HOME/.local/bin.

**Comment by wssheldon** [comment]
Thanks @JacobTravers, I agree, and I'll work on getting this changed.
