### ISSUE TITLE
[Feature Request] Censys Menu

### ISSUE THREAD

**Issue by thehappydinoa** [wssheldon/osintui#6]
Hi there,

This is a really cool project! I would love to be able to use Censys Search from this same tool. Is that something that might be on the roadmap for this project?

**Comment by wssheldon** [comment]
@thehappydinoa Thanks! This is definitely something I would like to add. Are there any specific endpoints and pieces of data you would be interested in seeing from the Censys API [0]? Additionally, do those endpoints require a paid API token and if so, would you be able to provide one?

[0] - https://search.censys.io/api#/

**Comment by thehappydinoa** [comment]
Hey there,

I think the IP lookup endpoint and the IP search endpoint are probably the best. And its actually free, just sign up for an account and you will get an API ID and Secret. 

If you run into any issues or want some assistance please feel free to reach out over GitHub, Twitter or email. 

Thanks,
Aidan

**Comment by thehappydinoa** [comment]
Thanks so much! This is really exciting!

**Comment by wssheldon** [comment]
Of course! As the UI components for Censys are pretty barebones right now, let me know if there's any information you'd like to have prioritized to be shown, and how it might be visualized.

**Comment by wssheldon** [comment]
> Of course! As the UI components for Censys are pretty barebones right now, let me know if there's any information you'd like to have prioritized to be shown, and how it might be visualized.

For context, I generally just try to replicate the web application front-end as much as possible.

**Comment by thehappydinoa** [comment]
Absolutely, I think that you have the important bits down, but I will totally let you know if I think of any!
