### ISSUE TITLE
reqwest::Error { kind: Decode, source: Error("missing field `whois`", line: 585, column: 9) }

### ISSUE THREAD

**Issue by xzripper** [wssheldon/osintui#8]
When i typing ip, and pressing enter i getting 400 error and 'reqwest::Error { kind: Decode, source: Error("missing field `whois`", line: 585, column: 9) }'

**Comment by wssheldon** [comment]
Thanks for reporting, definitely a poorly handled error. Can you share the IP that didn't work for you?

**Comment by BannersSecret** [comment]
Hi,

I am also getting a similar error:

![image](https://user-images.githubusercontent.com/10671939/196735887-cda8dbeb-6b6f-46e1-8a0b-d3fa3135a198.png)

It seems to behave differently depending on the IP I am looking at. For example, 8.8.8.8 doesn't respond with anything.

I've tried a number of IP addresses. I've double-checked my API keys and they are correct.

Any help would be really appreciated. This looks amazing.

**Comment by wssheldon** [comment]
Appreciate the additional information, I'll get this resolved as soon as I can.

**Comment by wssheldon** [comment]
This should be resolved. Please let me know if you are still encountering this issue after updating. Thank you again!

**Comment by xzripper** [comment]
ip is my :) yeah, error is fixed, thank!!

**Comment by wssheldon** [comment]
Glad to hear it! Let me know if you are into any other bugs or potential improvements by filing an issue.
